// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCVGv46dL7QrSj8oGBEWyc5pUFhxosmrw',
    appId: '1:281280678662:web:c14d43c2ee6af06a20ec87',
    messagingSenderId: '281280678662',
    projectId: 'e-bike-511f2',
    authDomain: 'e-bike-511f2.firebaseapp.com',
    storageBucket: 'e-bike-511f2.appspot.com',
    measurementId: 'G-0H4EHPVQMG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzQK0-vT9mhg_GOgTzxiRTc5iWEDxcLeY',
    appId: '1:281280678662:android:a7c798ac0907732e20ec87',
    messagingSenderId: '281280678662',
    projectId: 'e-bike-511f2',
    storageBucket: 'e-bike-511f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhFnqHKxB3gcPhYTGqzqBxL1eFKvyBONc',
    appId: '1:281280678662:ios:e271b2b1ac5117ab20ec87',
    messagingSenderId: '281280678662',
    projectId: 'e-bike-511f2',
    storageBucket: 'e-bike-511f2.appspot.com',
    iosBundleId: 'com.example.fairoosEbike',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhFnqHKxB3gcPhYTGqzqBxL1eFKvyBONc',
    appId: '1:281280678662:ios:a22ad326eae4372c20ec87',
    messagingSenderId: '281280678662',
    projectId: 'e-bike-511f2',
    storageBucket: 'e-bike-511f2.appspot.com',
    iosBundleId: 'com.example.fairoosEbike.RunnerTests',
  );
}
